//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meeting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EVENT
    {
        public decimal ID { get; set; }
        public string TEXT { get; set; }
        public Nullable<System.DateTime> EVENTSTART { get; set; }
        public Nullable<System.DateTime> EVENTEND { get; set; }
        public decimal CONFROOMID { get; set; }
        public decimal USERID { get; set; }
        public string STATUS { get; set; }
    
        public virtual MEETINGROOM MEETINGROOM { get; set; }
        public virtual USER USER { get; set; }
    }
}
